version: "3.8"

services:
    db:
        image: mysql:8.4
        container_name: db_sample
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            TZ: ${TZ}
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./data/db-store:/var/lib/mysql
