version: "3.8"

services:
    nextjs:
        image: nextjs_image
        container_name: nextjs_sample
        build:
            context: .
            dockerfile: ./next_sample/Dockerfile
        ports:
            - 3000:3000
